/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GamePackage {
  'id' : bigint,
  'diamonds' : bigint,
  'name' : string,
  'priceBDT' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export type PaymentMethod = { 'nagad' : null } |
  { 'bKash' : null };
export interface TopUpOrder {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'game' : string,
  'playerId' : string,
  'user' : Principal,
  'packageId' : bigint,
}
export interface _SERVICE {
  'addGamePackage' : ActorMethod<[string, bigint, bigint], bigint>,
  'createOrder' : ActorMethod<[string, string, bigint, PaymentMethod], bigint>,
  'getAllOrders' : ActorMethod<[], Array<TopUpOrder>>,
  'getGamePackages' : ActorMethod<[], Array<GamePackage>>,
  'getUserOrders' : ActorMethod<[Principal], Array<TopUpOrder>>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];