/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentMethod = IDL.Variant({
  'nagad' : IDL.Null,
  'bKash' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
});
export const TopUpOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'game' : IDL.Text,
  'playerId' : IDL.Text,
  'user' : IDL.Principal,
  'packageId' : IDL.Nat,
});
export const GamePackage = IDL.Record({
  'id' : IDL.Nat,
  'diamonds' : IDL.Nat,
  'name' : IDL.Text,
  'priceBDT' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addGamePackage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, PaymentMethod],
      [IDL.Nat],
      [],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(TopUpOrder)], ['query']),
  'getGamePackages' : IDL.Func([], [IDL.Vec(GamePackage)], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(TopUpOrder)], ['query']),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentMethod = IDL.Variant({ 'nagad' : IDL.Null, 'bKash' : IDL.Null });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const TopUpOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'game' : IDL.Text,
    'playerId' : IDL.Text,
    'user' : IDL.Principal,
    'packageId' : IDL.Nat,
  });
  const GamePackage = IDL.Record({
    'id' : IDL.Nat,
    'diamonds' : IDL.Nat,
    'name' : IDL.Text,
    'priceBDT' : IDL.Nat,
  });
  
  return IDL.Service({
    'addGamePackage' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, PaymentMethod],
        [IDL.Nat],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(TopUpOrder)], ['query']),
    'getGamePackages' : IDL.Func([], [IDL.Vec(GamePackage)], ['query']),
    'getUserOrders' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TopUpOrder)],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };