/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GamePackage {
    id: bigint;
    diamonds: bigint;
    name: string;
    priceBDT: bigint;
}
export interface TopUpOrder {
    id: bigint;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    game: string;
    playerId: string;
    user: Principal;
    packageId: bigint;
}
export enum OrderStatus {
    pending = "pending",
    completed = "completed",
    processing = "processing"
}
export enum PaymentMethod {
    nagad = "nagad",
    bKash = "bKash"
}
export interface backendInterface {
    addGamePackage(name: string, diamonds: bigint, priceBDT: bigint): Promise<bigint>;
    createOrder(playerId: string, game: string, packageId: bigint, paymentMethod: PaymentMethod): Promise<bigint>;
    getAllOrders(): Promise<Array<TopUpOrder>>;
    getGamePackages(): Promise<Array<GamePackage>>;
    getUserOrders(user: Principal): Promise<Array<TopUpOrder>>;
    updateOrderStatus(orderId: bigint, newStatus: OrderStatus): Promise<void>;
}
import type { OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, TopUpOrder as _TopUpOrder } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGamePackage(arg0: string, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGamePackage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGamePackage(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrder(arg0: string, arg1: string, arg2: bigint, arg3: PaymentMethod): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, to_candid_PaymentMethod_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, to_candid_PaymentMethod_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getAllOrders(): Promise<Array<TopUpOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGamePackages(): Promise<Array<GamePackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGamePackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGamePackages();
            return result;
        }
    }
    async getUserOrders(arg0: Principal): Promise<Array<TopUpOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_OrderStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TopUpOrder_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopUpOrder): TopUpOrder {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    paymentMethod: _PaymentMethod;
    game: string;
    playerId: string;
    user: Principal;
    packageId: bigint;
}): {
    id: bigint;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    game: string;
    playerId: string;
    user: Principal;
    packageId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n6(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n8(_uploadFile, _downloadFile, value.paymentMethod),
        game: value.game,
        playerId: value.playerId,
        user: value.user,
        packageId: value.packageId
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "processing" in value ? OrderStatus.processing : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nagad: null;
} | {
    bKash: null;
}): PaymentMethod {
    return "nagad" in value ? PaymentMethod.nagad : "bKash" in value ? PaymentMethod.bKash : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TopUpOrder>): Array<TopUpOrder> {
    return value.map((x)=>from_candid_TopUpOrder_n4(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    completed: null;
} | {
    processing: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.processing ? {
        processing: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    nagad: null;
} | {
    bKash: null;
} {
    return value == PaymentMethod.nagad ? {
        nagad: null
    } : value == PaymentMethod.bKash ? {
        bKash: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
